name: testtube
version: a0.0.0
debug: true

fw:
  name: qKit
  version: a0.0.1
  enableEasterEgg: true 
  enableqKitHeaders: true # This shows what version it uses on the header.

_db:
  host: localhost
  username: root
  password: nil
  name: nil

# you could use this for apis for extensions IF we were to support them
api:
  test: key